# Generated by Django 5.2.4 on 2025-07-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='correcao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpp.correcao'),
        ),
    ]
